AWSTemplateFormatVersion: "2010-09-09"
Description: Beginners challenge (tier 1). Implement a simple web server using AWS.

Parameters:
  EnvironmentName: 
    Description: An environment name that is prefixed to resource names
    Type: String
  
  DomainName:
    Description: The name of the domain. Specify a fully qualified domain name, for example, www.example.com
    Default: 'www.racoros-tier1.apperdevops.com'
    Type: String


  VpcCIDR:
    Description: CIDR block for VPC.
    Type: String
    Default: 10.1.0.0/16

  PublicSubnetCIDR:
    Description: CIDR block for public subnet.
    Type: String
    Default: 10.2.0.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.3.1.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.3.2.0/24

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

Resources:

  DNS:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref DomainName

 VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName



Outputs:

