
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCidr: 10.0.0.0/16
        PublicSubnetCIDR: 10.0.1.0/24
        PrivateSubnet1Cidr: 10.0.2.0/24
        PrivateSubnet2Cidr: 10.0.3.0/24
 

Outputs:
