AWSTemplateFormatVersion: "2010-09-09"
Description: Beginners challenge (tier 1). Implement a simple web server using AWS.

Parameters:
  EnvironmentName: 
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcCIDR:
    Description: CIDR block for VPC.
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Description: CIDR block for public subnet.
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1CIDR:
    Type: String
    Description: Private IP subnet used for AZ1.  Default "10.3.0.0/24"
    Default: 10.0.2.0/24
    AllowedPattern: ^([0-9]+\.){3}[0-9]+\/[0-9]+$
    MinLength: 9
    MaxLength: 18
    ConstraintDescription: Must be a valid CIDR range of the form x.x.x.x/x

  PrivateSubnet2CIDR:
    Type: String
    Description: Private IP subnet used for AZ2.  Default "10.3.0.0/24"
    Default: 10.0.3.0/24
    AllowedPattern: ^([0-9]+\.){3}[0-9]+\/[0-9]+$
    MinLength: 9
    MaxLength: 18
    ConstraintDescription: Must be a valid CIDR range of the form x.x.x.x/x

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnetCIDR

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC      
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock:
        Ref: PrivateSubnet1CIDR

  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock:
        Ref: PrivateSubnet2CIDR

Outputs:
  outputVpcId:
    Description: The id of the vpc resource that was created
    Value:
      Ref: VPC

  outputPublicSubnet:
    Description: The id of the vpc resource that was created
    Value:
      Ref: PublicSubnet
  outputPrivateSubnets:
    Description: Private subnets for each AZ as comma-separted list
    Value:
      Fn::Join:
      - ','
      - - !Ref PrivateSubnetAZ1
        - !Ref PrivateSubnetAZ2
  