AWSTemplateFormatVersion: '2010-09-09'

Description: AWS templates provisions SSL certificates via certificate manager

Parameters:
  DomainName:
    Default: racoros-tier1.apperdevops.com
    Description: Domain name for the application.
    Type: String

Resources:
  CertificateManager:
    Type: AWS::CertificateManager::Certificate
    Properties:
        DomainName: !Ref DomainName
        ValidationMethod: DNS

Outputs:
  Certificate:
    Description: The Created Certificate
    Value: !Ref CertificateManager
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-Certificate'